- block:
    - block:
        - name: get rid of RHUI repo files if present
          file:
            path: "{{ item }}"
            state: absent
          with_items:
            - "/etc/yum.repos.d/redhat-rhui.repo"
            - "/etc/yum.repos.d/redhat-rhui-client-config.repo"
            - "/etc/yum.repos.d/rhui-load-balancers.conf"

        - name: register with RHN
          redhat_subscription:
            state: present
            username: "{{ rhn_username }}"
            password: "{{ rhn_password }}"
            autosubscribe: false
          ignore_errors: yes

        - name: unsub everything
          shell: subscription-manager unsubscribe --all
          ignore_errors: yes

        - name: subscribe to pool
          shell: subscription-manager subscribe --pool "{{ rhn_pool }}"
          ignore_errors: no

        - name: disable all repos
          shell: subscription-manager repos --disable="*"

        - name: enable Gluster repos
          shell: subscription-manager repos --enable="{{ item }}"
          with_items: "{{ repo_names }}"
      tags:
        - subscription_manager

    - name: update RHEL
      yum:
        name: '*'
        state: latest

    - name: remove firewalld
      yum:
        name: firewalld
        state: absent

    - name: ensure firewall rules are flushed
      shell: iptables --flush

    - name: install Gluster packages
      yum:
        name: redhat-storage-server
        state: latest
      register: gluster_installed

#    - debug: var=gluster_installed.results[0]
#    - block:
#        - name: restart Gluster nodes
#          command: "shutdown -r now"
#          async: 0
#          poll: 0
#          ignore_errors: yes
#
#        - name: Wait for SSH to come up on public instances
#          local_action: wait_for host={{ item.public_dns_name }} port=22 delay=0 timeout=600 state=started
#          with_items:
#            - "{{ ec2_instances }}"
#
#        - name: Wait for successful SSH
#          local_action: command "ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null {{ ec2_username }}@{{ item.public_dns_name }} echo host is up"
#          with_items:
#            - "{{ ec2_instances }}"
#          register: result
#          until: result.rc == 0
#          retries: 10
#          delay: 60
#      when: "'packages providing redhat-storage-server are up to date' not in gluster_installed.results[0]"

  tags:
    - gluster_install